from tkinter import*
root=Tk()
root.geometry("800x800")
heading=Label(root,text="welcome to wiki-vepedia",font="algerian 20 bold")
heading.grid(row=0,column=3)
name = Label(root, text="Name")
phonenumber=Label(root,text="Phonenumber")
gender=Label(root,text="Gender")
password=Label(root,text="password")
name.grid(row=1,column=3)
phonenumber.grid(row=2,column=3)
gender.grid(row=3,column=3)
password.grid(row=4,column=3)
namevalue = StringVar()
phonevalue = StringVar()
gendervalue = StringVar()
passwordvalue = StringVar()
verifyvalue = IntVar()
nameentry = Entry(root, textvariable=namevalue)
phoneentry = Entry(root, textvariable=phonevalue)
genderentry = Entry(root, textvariable=gendervalue)
passwordentry = Entry(root, textvariable=passwordvalue)
nameentry.grid(row=1, column=4)
phoneentry.grid(row=2, column=4)
genderentry.grid(row=3, column=4)
passwordentry.grid(row=4, column=4)
verify = Checkbutton(text="I am not a ROBOT", variable = verifyvalue)
verify.grid(row=6, column=4)
Button(text="Submit to ADMIN").grid(row=7, column=4)
root.mainloop()